---
# 1) Simple log generator Deployment (no Service needed)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: bastion-example
  labels:
    app.kubernetes.io/name: log-generator   # <-- used by your transform as service.name
    app: log-generator                      # <-- optional alias if you also map plain 'app'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: log-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: log-generator
        app: log-generator
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: loggen
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          env:
            # ~2 logs/sec; raise to increase, lower to reduce
            - name: RATE_MS
              value: "500"
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
          command: ["/bin/sh","-c"]
          args:
            - |
              i=0
              while true; do
                i=$((i+1))
                ts="$(date -u +%FT%TZ)"
                case $((RANDOM % 10)) in
                  0) lvl="error";; 1|2) lvl="warn";; *) lvl="info";;
                esac
                printf '{"timestamp":"%s","level":"%s","message":"hello from log-generator","service_name":"%s","pod":"%s","namespace":"%s","node":"%s","sequence":%d}\n' \
                       "$ts" "$lvl" "$SERVICE_NAME" "$POD_NAME" "$POD_NAMESPACE" "$NODE_NAME" "$i"
                usleep $(( (${RATE_MS:-500}) * 1000 ))
              done
          tty: false
          stdin: false
